# Generated by Django 2.2.3 on 2020-07-31 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7)),
                ('date_of_birth', models.DateField()),
                ('Year_of_Graduation', models.DateField()),
                ('Sch_of_Graduation', models.CharField(max_length=255)),
                ('Hospital_of_housemanship', models.CharField(max_length=255)),
                ('Folio_Number', models.CharField(max_length=50)),
                ('Full_License', models.FileField(upload_to='../media/License_document/%Y/%m/%d/')),
                ('Evidence_of_License_Reg', models.FileField(upload_to='../media/Evidence_of_Annual_License_Reg/%Y/%m/%d/')),
                ('CV', models.FileField(upload_to='../media/CV/%Y/%m/%d/')),
                ('Specialization', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('UserProfile.profile', models.Model),
        ),
    ]
