# Generated by Django 2.2.3 on 2020-07-21 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('active', models.BooleanField(default=False)),
                ('Year_of_Graduation', models.DateField()),
                ('Sch_of_Graduation', models.CharField(max_length=150)),
                ('Hospital_of_housemanship', models.CharField(max_length=255)),
                ('Folio_Number', models.CharField(max_length=50)),
                ('Full_License_document', models.ImageField(upload_to='License_document/%Y/%m/%d/')),
                ('Evidence_of_Annual_License_Reg', models.ImageField(upload_to='Evidence_of_Annual_License_Reg/%Y/%m/%d/')),
                ('CV', models.ImageField(upload_to='CV/%Y/%m/%d/')),
                ('Specialization', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('UserProfile.profile', models.Model),
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('UserProfile.profile', models.Model),
        ),
    ]
