# Generated by Django 2.2.3 on 2020-07-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_doctorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
