# Generated by Django 2.2.3 on 2020-07-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_doctorprofile_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='active',
        ),
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
