# Generated by Django 2.2.3 on 2020-07-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0004_auto_20200721_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='active',
            new_name='checked',
        ),
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
